apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-project-deployment
spec:
  selector:
    matchLabels:
      app: kiii-project
  replicas: 2
  template:
    metadata:
      labels:
        app: kiii-project
    spec:
      containers:
        - name: project
          image: flepceska/kiii-project
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: project-k8ssvc
spec:
  selector:
    app: kiii-project
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort