version: '3'
services:
  database:
    container_name: kiii_project_database
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=kiii123
      - POSTGRES_DB=kiii_project
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5454:5432
  kiii_poject:
    depends_on:
      - database
    image: kiii_project.jar
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postresql://postgres:5432/kiii_project
    ports:
      - "8080:8080"
volumes:
  postgres-data:
    driver: local